### ISSUE TITLE
Ich würde die TEI-Dateien in .txt speichern, und nicht .odt

### ISSUE THREAD

**Issue by dareiadareia** [dareiadareia/nicolaus-oresme#1]

**Comment by PanzicaA** [comment]
Ok! Und warum?
Was deine Frage bzgl. der Nummern für die Handschriften: Ich habe die Nummer 2197, 4375 und 753 ausgewählt, weil sie einfach die Signaturnummer der Handschriften sind, und daher einfacher zu merken :-) schau die Signaturen!

**Comment by dareiadareia** [comment]
Weil .txt das alleeeinfachste Format ist und nichts außer bloßem Text hat :) 
Ach so! Jetzt verstehe ich. Danke für die Erklärung!

**Comment by PanzicaA** [comment]
Eine Frage zur Publikation: Ich schaue jetzt die Powerpoint des Professors. Vorlesung 9, slide 9, schreibt er "Web-publishing via GitHub pages" -- was bedeutet es deiner Meinung nach? Kann man eigentlich auf GitHub etwas veröffentlichen? Oder meint er einfach das "hosting"?

**Comment by dareiadareia** [comment]
Es heißt, wenn wir in _nicolaus-oresme_ alle Dateien für Website haben (index.html, styles.css etc.), wir können eine Webseite erstellen, ohne es außer zu hosten (>> [link](https://pages.github.com))
P. S. Übrigens: ich glaube, hier sollte man für jedes Problem/Thema eine "Issue" öffnen;)

**Comment by PanzicaA** [comment]
Ok, danke für die Erklärung. Das hilft uns aber nicht weiter mit der Publikation, oder?
Ja, stimmt, man sollte jedes Thema separat besprechen, aber ich habe so gemacht, weil ich fürchte, das es ein bisschen verwirrend bekommen könnten - ausserdem haben wir ein kleines Projekt. Aber wenn du denkst, dass es im Gegenteil klarer würde, können wir auch so machen.
Ps: Und was denkst du zu den Folionumbrüchen?

**Comment by dareiadareia** [comment]
Nein, es hilft nicht so viel :( 

Ich bin nicht sicher; ich habe hier auch ein Projekt angefangen, da konnte man nützliche Links sammeln... Wir haben schon viele E-Mails, und es ist schon mühsam, dadrin etwas zu finden. Aber es geht mit einer Diskussion auch :) 

Zu den Foliounbrüchen: es scheint eine gute Idee zu sein; ich habe gerade [eine alte Webseite](http://tei.oucs.ox.ac.uk/Projects/EETS/soton/mstrans.htm) (aus 2003!) gefunden, wo es genau so gemacht wurde.

P. S. Kannst du deine .odt-Datei in .txt umsetzen und _commit change_?

**Comment by PanzicaA** [comment]
Hallo! Ich habe das das txt. Datei hochgeladen!
Was machen wir für die nächste Schritte?
Hast du das Visualization Programm probiert?
Bis Mittwoch habe ich ziemlich voll, ab Donnerstag geht es wieder besser. Morgen nach dem Seminar habe ich leider keine Zeit - ich muss sogar früher gehen, weil ich in Freiburg eine Sitzung des Nationalfonds habe.

**Comment by dareiadareia** [comment]
Hallo!
Also, ich wir müssen jetzt das ganze in TEI kodieren (das kann man sicher ziemlich einfach teilen) und die Fragen dem Professor stellen. 
Dann sollten wir mit Visualization zurecht kommen. Ehrlich gesagt, ich hatte gar keine Zeit, etwas auszuprobieren. Mache aber vielleicht noch heute/morgen.

**Comment by dareiadareia** [comment]
Hallo :)
Ich glaube, wir sollten für die Publikation am besten [TEI Boilerplate](https://github.com/GrantLS/TEI-Boilerplate) verwenden: 

> In teaching contexts, TEI Boilerplate is a useful solution. Students and scholars new to TEI are rightly excited and enthused as they encode their first documents and experience the expressive power of TEI markup. But too often that initial excitement and enthusiasm dissipate when new TEI users inquire about publishing their documents on the web and are confronted with sometimes overwhelming details about an unfamiliar programming language, XSLT, and other information about server-side processing and transformation engines. With TEI Boilerplate, users can simply add a single line of code to their documents to instruct modern browsers to produce formatted output of their TEI content. And that default TEI Boilerplate output may be further tweaked and customized using CSS.

**Comment by PanzicaA** [comment]
Ok, super! Weisst du, wie das man benutzt? Soll man es einfach herunterladen? Ich würde sagen, dass es gut wäre, dass wir bis Ende dieser Woche etwas fertig haben könnten. Ich kann mit dem TEI weitermachen, du kannst das mit dem Veröffentlichung anschauen (und vielleicht mit einem Teil des TEI probieren), und Jelena könnte das Bericht weiterschreiben. A propos Jelena: kannst du das Dokument, das du bis jetzt geschrieben hast, auf Github hochladen? Einen schönen Abend.

**Comment by PanzicaA** [comment]
Ich habe folgendes auf der Boilerplate Webseite gefunden: Download the TEI Boilerplate files, and host the dist directory on a web server.

The simplest way to use TEI Boilerplate (TEIBP) is simply to add your TEI files to the dist/content directory of TEI Boilerplate and include the following xml-stylesheet processing instruction at the top of your TEI documents, after the XML declaration and before the root <TEI> element:

<?xml-stylesheet type="text/xsl" href="teibp.xsl"?>
You may then access your TEI files from a modern browser and see the resulting styled document.

---> was bedeutet genau " host the dist directory on a web server"?

**Comment by dareiadareia** [comment]
Ja gerne, ich versuche morgen verstehen, wie das alles mit Boilerplate funktioniert. 
Und "host the directory on a web server" muss einfach heißen, unsere Dateien müssen im Internet sein und nicht auf dem PC ;)

**Comment by dareiadareia** [comment]
Übrigens, ich habe herausgefunden, wie man Handschriftenbilder in TEI verlinken kann:
`<pb facs=".../images/page01.jpg"/>`
Ich schlage vor, machen wir einen 'images' Ordner in nicolaus-oresme dafür.

**Comment by dareiadareia** [comment]
Hallo wieder,
zu den Varianten:

Ich finde, wir müssen die "om.", "add." etc. supprimieren, weil sie nicht zum Text gehören. Wir können vielleicht das Problem lösen, indem wir zwei Text-Varianten kodieren (und wo es keinen Text gibt, wird der Code so aussehen: `<rdg wit="#p753"></rdg>`).

**Comment by dareiadareia** [comment]
...und zu den Quellen:
wir brauchen einen Bezug im Text, damit die Quelle oben erscheinen kann; den kann man mit dem `<ref>` Element kodieren. 
Ein Stück TEI wird also wie Folgendes aussehen:
`...et <ref>Aristoteles in textu, capitulo tertio</ref><note>Aristoteles, Meteorologica, I, 3, 341 b 15-25.</note>, probat quod ignis movetur circulariter in sua spera...`

Im Browser sieht man die Quellenangabe nur wenn man mit der Maus darüber fährt: 
![note-hover-example](https://cloud.githubusercontent.com/assets/22611808/21074066/356b5e42-beef-11e6-91ae-c16217986d5e.jpg)

**Comment by PanzicaA** [comment]
Hallo Daria,

ich werde später das mit den Quellen machen und die Bilder der Handschriften auf GitHub hochladen. Eine Frage: wo muss man dieses Element <pb facs=".../images/page01.jpg"/> im TEI kodieren? Z.B. in diesem Fall [C53r]?

**Comment by dareiadareia** [comment]
Ich bin nicht ganz sicher, scheint aber so zu sein: 

Quia in precedenti questione dictum est [M 20vb] quod...  >> 
`Quia in precedenti questione dictum est <pb facs="images/M/20vb.jpg"/> quod... `

Wie es auf der Webseite gezeigt werden kann, habe ich noch nicht so gut verstanden.
