### ISSUE TITLE
Visualisation

### ISSUE THREAD

**Issue by PanzicaA** [dareiadareia/nicolaus-oresme#3]
Hallo zusammen,

Wie machen wir weiter mit der Visualisierung? Daria, weisst du, wann du dein Laptop haben wirst? Kann ich etwas inzwischen machen? Z.B. bringt was, wenn ich es mit dem EVT versusche?

**Comment by dareiadareia** [comment]
Hallo Aurora,
ich habe mich die Bilder angeschaut; sind diese der Handschrift D nur in diesem Format (als Screenshots?..) vorhanden?

**Comment by PanzicaA** [comment]
Hallo Daria,
nein, ich habe auch ein Pdf. Das Problem ist aber, das ich ein einziges Pdf für die Handschrift habe und nicht weiss, wie ich die Teilen, die un betreffen, ausscheiden kann. Desalb habe ich Screenshots gemacht :-)
